name: Release Agent

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"

jobs:
  release-agent:
    name: Release Agent
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/github.com/aws/amazon-ecs-agent
    steps:
      - uses: actions/checkout@v4
        with:
          # TODO: remove `ref` so that it defaults to the SHA of the event that triggered the workflow (push to dev).
          ref: dev
          path: src/github.com/aws/amazon-ecs-agent
          fetch-depth: 0
      - name: Disable branch protection rule
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -ex
          branchProtectionRule = $(gh api graphql -f query='
          {
            repository(owner: ${{ github.repository_owner }}, name: ${{ github.event.repository.name }}) {
              ref(qualifiedName: "master") {
                branchProtectionRule {
                  id
                }
              }
            }
          }' | jq ".data.repository.ref.branchProtectionRule.id")
          echo $brachProtectionRule
      - name: Merge dev into master
        env:
          # Create the pull request using amazon-ecs-bot's token instead of $GITHUB_TOKEN
          # so that status check workflows still run on the pull request.
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
          GH_TOKEN: ${{ secrets.ECS_AGENT_WORKFLOW_SECRET }}
        run: |
          set -ex
          # TODO: replace --head with the SHA of the event that triggered the workflow.
          pr_url=$(gh pr create --fill-first --base master --head dev)
          gh pr merge $pr_url --auto -m
