name: Release Agent

on:
  push:
    branches: [ "dev" ]

jobs:
  release-agent:
    name: Release Agent
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/github.com/aws/amazon-ecs-agent
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          # TODO: remove `ref` so that it defaults to the SHA of the event that triggered the workflow (push to dev).
          ref: dev
          path: src/github.com/aws/amazon-ecs-agent
          fetch-depth: 0
      - name: Merge dev into master
        run: |
          set -ex
          git push origin HEAD:master
