name: Release Agent

on:
  push:
    branches: [ "dev" ]

jobs:
  release-agent:
    name: Release Agent
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/github.com/aws/amazon-ecs-agent
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev
          path: src/github.com/aws/amazon-ecs-agent
      - name: Merge dev into master
        run: |
          set -ex
          git fetch origin master
          git show-ref
          git push -vvv origin master
