name: Release Agent

on:
  push:
    branches: [ "dev" ]

jobs:
  release-agent:
    name: Release Agent
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/github.com/aws/amazon-ecs-agent
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev
          path: src/github.com/aws/amazon-ecs-agent
      - name: Merge dev into master
        run: |
          set -ex
          git log HEAD
          git log refs/remotes/origin/master
          git push origin HEAD:master
