name: Release Pull Request

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true

jobs:
  release-pull-request:
    name: Release Pull Request
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    defaults:
      run:
        working-directory: src/github.com/aws/amazon-ecs-agent
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev
          path: src/github.com/aws/amazon-ecs-agent
      - name: Get GO_VERSION
        run: |
          set -eou pipefail
          go_version=$(cat -e GO_VERSION)
          go_version=${go_version%?}
          go_version_length=${#go_version}
          go_version_re="^([0-9]+\.){1,2}([0-9]+)$"
          if ! [[ $go_version_length -le 10 && $go_version =~ $go_version_re ]] ; then
            echo "invalid GO version"
            exit 1
          fi
          echo "GO_VERSION=$go_version" >> $GITHUB_OUTPUT
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ steps.get-go-version.outputs.GO_VERSION }}
      - name: Update CHANGELOG
        run: |
          set -ex
          : # TODO: update CHANGELOG, exiting early with error if version already exists
      - name: Update VERSION
        run: |
          set -ex
          echo ${{ inputs.version }} > VERSION
          export GOPROXY=direct
          cd agent/version
          GO111MODULE=off go run gen/version-gen.go
      - name: Open Pull Request
        run: |
          set -ex
          commit_message="Release ${{ inputs.version }}"
          git_branch="v${{ inputs.version }}"
          git checkout -b $git_branch
          git add -A
          # Commit as the github-actions bot.
          # https://github.com/actions/checkout?tab=readme-ov-file#push-a-commit-using-the-built-in-token
          git -c user.name="github-actions[bot]" \
            -c user.email="41898282+github-actions[bot]@users.noreply.github.com" \
            commit -m "$commit_message"
          git push --set-upstream origin $git_branch
          gh pr create \
            --title "$commit_message" \
            --body "TODO" \
            --base dev \
            --head $git_branch
          
          
