name: Release Pull Request

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true

jobs:
  release-pull-request:
    name: Release Pull Request
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/github.com/aws/amazon-ecs-agent
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev
          path: src/github.com/aws/amazon-ecs-agent
      - name: Update CHANGELOG
        run: |
          set -ex
          pwd
          : # TODO: update CHANGELOG, exiting early with error if version already exists
          grep ${{ inputs.version }} CHANGELOG.md
      - name: Update VERSION
        run: |
          set -ex
          echo ${{ inputs.version }} > VERSION
          
